### ISSUE TITLE
dev-set "qid"="a5dda44918d33681714638f30fba1663"のデータについて

### ISSUE THREAD

**Issue by yano0** [aiishii/JEMHopQA#1]
有用なデータセットの作成、公開ありがとうございます！

dev-set内の"qid"="a5dda44918d33681714638f30fba1663"のデータにつきまして、「『ワイルド・スピード\/スーパーコンボ』の前の話にあたる作品の監督はは誰？」という問いに対し、「クリス・モーガン」が解答になっています。しかし、[『ワイルド・スピード\/スーパーコンボ』](https://ja.wikipedia.org/wiki/%E3%83%AF%E3%82%A4%E3%83%AB%E3%83%89%E3%83%BB%E3%82%B9%E3%83%94%E3%83%BC%E3%83%89/%E3%82%B9%E3%83%BC%E3%83%91%E3%83%BC%E3%82%B3%E3%83%B3%E3%83%9C)の前の話とされている『ワイルド・スピード ICE BREAK』の[Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%AF%E3%82%A4%E3%83%AB%E3%83%89%E3%83%BB%E3%82%B9%E3%83%94%E3%83%BC%E3%83%89_ICE_BREAK)によるとクリス・モーガンは脚本家であり、監督はF・ゲイリー・グレイのようです。

ご確認いただけますと幸いです。

**Comment by aiishii** [comment]
ご連絡ありがとうございます。
間違いがあり申し訳ありませんでした。
ご指摘の間違いを含み、いくつかの修正をした版をver1.1として公開いたしました。
引き続きご利用いただけますと幸いです。
